version: '3.10'

services:
  pyro-scrapper:
    image: pyronear/pyro-scrapper:latest
    command: sleep infinity
    volumes:
      - /media/mateo/T7/AWF_scrap:/usr/src/app/AWF_scrap
    restart: always
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
